name: article-cleanup

on:
  workflow_dispatch:
    inputs:
      favorite_word:
        description: "What's your favorite word? [No wrong answers.]"
        required: true
      confirmation:
        description: "Type 'YES' to continue with the cleanup. CASE SENSITIVE!"
        required: true
      input_passcode:
        description: "Input passcode for 2nd Level authorization."
        required: true

jobs:
  validate_and_cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Validate and Perform Cleanup
        run: |
          # Get user inputs
          favorite_word="${{ github.event.inputs.favorite_word }}"
          confirmation="${{ github.event.inputs.confirmation }}"
          input_passcode="${{ github.event.inputs.input_passcode }}"
          secret_passcode="${{ secrets.CLEANUP_PASSCODE }}"

          # Echo the favorite word
          echo
          echo "Your favorite word is: $favorite_word"
          echo

          # Check confirmation
          if [ "$confirmation" != 'YES' ]; then
            echo "Cleanup canceled by user."
            exit 1
          fi

          # Check passcode
          if [ "$input_passcode" != "$secret_passcode" ]; then
            echo "Incorrect passcode. Exiting workflow."
            exit 1
          else
            echo "Action authorized. Proceeding with cleanup. DO NOT SHARE THE PASSCODE!"
          fi

          # Check for 'articles' folder and perform cleanup operations
          echo "Performing cleanup operations..."
          sleep 1
          echo "Finding 'articles/' folder..."

          # Check if the 'articles' folder exists in the current directory
          if [ -d "articles" ]; then
            echo "Folder exists. Proceeding with the clean up."
            rm -rf articles/*
            echo "Clean up successful!"
          else
            echo "Folder doesn't exist. Exiting the workflow..."
            exit 1
          fi