name: Delete Files/Folders

on:
  workflow_dispatch:
    inputs:
      folder_to_delete:
        description: 'Path of the folder to delete'
        required: true
      access_code:
        description: 'Access code for cleanup'
        required: true
        type: string

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Validate Access Code
      run: |
        if [ "${{ secrets.CLEANUP_PASSCODE }}" != "${{ github.event.inputs.access_code }}" ]; then
          echo "Error: Invalid access code"
          exit 1
        fi

    - name: Delete folder
      run: |
        folder="${{ github.event.inputs.folder_to_delete }}"
        if [ -d "$folder" ] || [ -f "$folder" ]; then
          echo "Deleting folder or file: $folder"
          rm -rf "$folder"
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add -A
          git commit -m "Deleted $folder"
          git push
        else
          echo "Error: Folder or file '$folder' does not exist"
          exit 1
        fi