name: Scrape Editorials

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 6 * * *'  # Scheduled trigger (runs at 6:00 AM UTC)

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Scrape Philstar and Inquirer Editorials
      run: |
        python scrape.py

    - name: Commit Editorials
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add articles/txt/inquirer-$(date +%Y%m%d).txt articles/txt/philstar-$(date +%Y%m%d).txt articles/md/inquirer-$(date +%Y%m%d).md articles/md/philstar-$(date +%Y%m%d).md
        git commit -m "Updated Philstar and Inquirer editorials for $(date +'%b. %d, %Y (%a)')"
        git push